### ISSUE TITLE
Napaka pri prevajanju poročila

### ISSUE THREAD

**Issue by katarinabrilej** [aljazkump/APPR-2021-22#3]
Poročilo se ne prevede - pri branju datotek je namesto encoding potrebno napisati fileEncoding. Tako se bodo imena držav prebrala s šumniki in bo potrebno spremeniti še nekaj stvari (npr. pri klicanju stolpca Hrvaska).

**Comment by katarinabrilej** [comment]
Napaka je tudi pri tabeli Aktivnost in sicer
```
Error in `$<-.data.frame`(`*tmp*`, Status, value = c("Mladi", "Mladi",  : 
  replacement has 40 rows, data has 10
```

**Comment by aljazkump** [comment]
Popravil sem napake

**Comment by M4rble** [comment]
Poročilo se še vedno ne prevede. Vidim, da si dodal fileEncoding - to pomeni, da se ti bodo sedaj datoteke prebrale s šumniki. Zato moraš popraviti klicanje vseh stolpcev, ki vsebujejo šumnike (torej namesto Hrvaska kliči Hrvaška, namesto Nemcija kliči Nemčija itd.)

**Comment by aljazkump** [comment]
Besedam sem dodal šumnike.

**Comment by aljazkump** [comment]
fileEncoding sem spremenil v UTF-8, zdaj bi res moralo vse delovati

**Comment by M4rble** [comment]
Sedaj deluje, projekt bo popravljen v prihodnjih dneh.

**Comment by katarinabrilej** [comment]
Pri grafih/zemljevidih je potrebno popraviti naslednje stvari:
manjkajo naslovi, imena v legendah niso popravljena, manjkajo naslovi legend, oznake osi niso povsod jasne, npr. pri histogramih oznaka osi y, ...
