### ISSUE TITLE
Ocena projekta

### ISSUE THREAD

**Issue by katarinabrilej** [aljazkump/APPR-2021-22#4]
Projekt še vedno ni ocenjen pozitivno:

* problem je še vedno manjkajoča napredna analiza, torej razvrščanja sploh ni, prav tako ni izbire optimalnega modela pri linearni regresiji (narejeno je samo prileganje podatkom)

* uvoz: tabele še vedno niso v pravi obliki, samo csv format (ni html, xls), niso uporabljeni regularni izrazi, spodaj je primer pravilnega uvoza tabele:
```
Starost_Evropa <- read.csv(
  "podatki/starost_tujina.csv",
  fileEncoding = "UTF-8"
)
Starost_Evropa <- Starost_Evropa %>% mutate(Starost = rep(c("Mladi", "Zreli", "Stari"), 
                                    each = length(unique(Leto)))) %>%
   pivot_longer(-c("Leto", "Starost"), names_to = "Drzava", values_to = "Stevilo")
```

Seveda je potem z uporabo regularnih izrazov potrebno odstraniti pike v imenih držav.

Podoben postopek je potrebno narediti za tabelo `Starost_Izobrazba_Spol` - ko je tabela urejena, se je potem ne ločuje na različne tabele glede na starost in spol (za namene vizualizacije), ampak se graf riše iz te urejene tabele, kjer npr. barvo črte določamo glede na neko spremenljivko, ne uporabimo torej za vsak spol znova geom_line()

* Skoraj ni predeleva podatkov (npr. grupiranja in računanja povprečja), združevanje tabel ni korektno in trivialno

* pri prostorski vizualizaciji je samo en slabo označen in slabo pojasnjen zemljevid, brez legende

* pri grafih imena v legendah niso spremenjena, legende nimajo naslovov, oznake osi niso povsod jasne/jih ni, pomankljivo pojasnjeni grafi

* poročilo je prekratno, ni zaključka, veliko je slovničnih napak,...

Točkovanje je naslednje (34 točk)

Predstavitev 2/5
Inovativnost pri izbiri podatkov za analizo 5/10
Zahtevnost priprave (uvoza in pred-obdelave) podatkov 5/20
Vizualizacija podatkov 12/20
Napredna analiza: razvrščanje in napovedovanje 3/25
Poročilo 5/15
Samostojnost 2/5

Če popravke oddaš v dveh dneh lahko pristopiš k ustnem izpitu v tem roku, v nasprotnem pa lahko projekt oddaš v naslednjem roku.

Lep pozdrav,
Katarina Brilej

**Comment by aljazkump** [comment]
Oddajam popravljen projekt:
- uvozil sem tudi iz xml formata
- uporabil sem več regularnih izrazov
- pri napredni analizi sem narisal dendogram in razvrstil v skupine
- pojasnil sem zakaj sem uporabil ustrezno regresijo
